// <auto-generated />
using System;
using ClinicFlowDemo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicFlowDemo.Migrations
{
    [DbContext(typeof(ClinicFlowDbContext))]
    partial class ClinicFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicFlowDemo.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("AppointmentDatetime")
                        .HasColumnType("datetime");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("AppointmentId");

                    b.HasIndex("PatientId");

                    b.HasIndex("RoomId");

                    b.HasIndex("ProviderId", "AppointmentDatetime")
                        .IsUnique()
                        .HasDatabaseName("UQ_Appointment_Provider_Datetime");

                    b.ToTable("Appointment", (string)null);
                });

            modelBuilder.Entity("ClinicFlowDemo.Models.ClinicLocation", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("LocationId");

                    b.HasIndex("Address")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ClinicLocation", (string)null);
                });

            modelBuilder.Entity("ClinicFlowDemo.Models.DiagnosisCode", b =>
                {
                    b.Property<string>("DiagnosisCodeValue")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("diagnosis_code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("DiagnosisCodeValue");

                    b.ToTable("DiagnosisCode", (string)null);
                });

            modelBuilder.Entity("ClinicFlowDemo.Models.Encounter", b =>
                {
                    b.Property<int>("EncounterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EncounterId"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EncounterDate")
                        .HasColumnType("date");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.HasKey("EncounterId");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.ToTable("Encounter", (string)null);
                });

            modelBuilder.Entity("ClinicFlowDemo.Models.EncounterDiagnosis", b =>
                {
                    b.Property<int>("EncounterId")
                        .HasColumnType("int");

                    b.Property<string>("DiagnosisCodeValue")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("diagnosis_code");

                    b.HasKey("EncounterId", "DiagnosisCodeValue");

                    b.HasIndex("DiagnosisCodeValue");

                    b.ToTable("EncounterDiagnosis", (string)null);
                });

            modelBuilder.Entity("ClinicFlowDemo.Models.Medication", b =>
                {
                    b.Property<int>("MedicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicationId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("MedicationId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Medication", (string)null);
                });

            modelBuilder.Entity("ClinicFlowDemo.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("HomeAddress")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("PatientId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Patient", (string)null);
                });

            modelBuilder.Entity("ClinicFlowDemo.Models.PatientPolicy", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("PatientId", "PolicyId");

                    b.HasIndex("PatientId")
                        .IsUnique()
                        .HasDatabaseName("UQ_PatientPolicy_OnePrimary")
                        .HasFilter("[IsPrimary] = 1");

                    b.HasIndex("PolicyId", "MemberId")
                        .IsUnique();

                    b.ToTable("PatientPolicy", (string)null);
                });

            modelBuilder.Entity("ClinicFlowDemo.Models.Policy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyId"));

                    b.Property<string>("PayerName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("PolicyId");

                    b.HasIndex("PayerName", "PlanName")
                        .IsUnique();

                    b.ToTable("Policy", (string)null);
                });

            modelBuilder.Entity("ClinicFlowDemo.Models.Prescription", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescriptionId"));

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("EncounterId")
                        .HasColumnType("int");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("MedicationId")
                        .HasColumnType("int");

                    b.HasKey("PrescriptionId");

                    b.HasIndex("EncounterId");

                    b.HasIndex("MedicationId");

                    b.ToTable("Prescription", (string)null);
                });

            modelBuilder.Entity("ClinicFlowDemo.Models.Provider", b =>
                {
                    b.Property<int>("ProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProviderId"));

                    b.Property<string>("Credentials")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("ProviderId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Provider", (string)null);
                });

            modelBuilder.Entity("ClinicFlowDemo.Models.ProviderLocation", b =>
                {
                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.HasKey("ProviderId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("ProviderLocation", (string)null);
                });

            modelBuilder.Entity("ClinicFlowDemo.Models.ProviderSpecialty", b =>
                {
                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("int");

                    b.HasKey("ProviderId", "SpecialtyId");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("ProviderSpecialty", (string)null);
                });

            modelBuilder.Entity("ClinicFlowDemo.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("RoomId");

                    b.HasIndex("LocationId", "Name")
                        .IsUnique();

                    b.ToTable("Room", (string)null);
                });

            modelBuilder.Entity("ClinicFlowDemo.Models.Specialty", b =>
                {
                    b.Property<int>("SpecialtyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecialtyId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("SpecialtyId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Specialty", (string)null);
                });

            modelBuilder.Entity("ClinicFlowDemo.Models.Appointment", b =>
                {
                    b.HasOne("ClinicFlowDemo.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicFlowDemo.Models.Provider", "Provider")
                        .WithMany("Appointments")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicFlowDemo.Models.Room", "Room")
                        .WithMany("Appointments")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Provider");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("ClinicFlowDemo.Models.Encounter", b =>
                {
                    b.HasOne("ClinicFlowDemo.Models.Appointment", "Appointment")
                        .WithOne("Encounter")
                        .HasForeignKey("ClinicFlowDemo.Models.Encounter", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("ClinicFlowDemo.Models.EncounterDiagnosis", b =>
                {
                    b.HasOne("ClinicFlowDemo.Models.DiagnosisCode", "DiagnosisCode")
                        .WithMany("EncounterDiagnoses")
                        .HasForeignKey("DiagnosisCodeValue")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicFlowDemo.Models.Encounter", "Encounter")
                        .WithMany("EncounterDiagnoses")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiagnosisCode");

                    b.Navigation("Encounter");
                });

            modelBuilder.Entity("ClinicFlowDemo.Models.PatientPolicy", b =>
                {
                    b.HasOne("ClinicFlowDemo.Models.Patient", "Patient")
                        .WithMany("PatientPolicies")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicFlowDemo.Models.Policy", "Policy")
                        .WithMany("PatientPolicies")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("ClinicFlowDemo.Models.Prescription", b =>
                {
                    b.HasOne("ClinicFlowDemo.Models.Encounter", "Encounter")
                        .WithMany("Prescriptions")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicFlowDemo.Models.Medication", "Medication")
                        .WithMany("Prescriptions")
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Encounter");

                    b.Navigation("Medication");
                });

            modelBuilder.Entity("ClinicFlowDemo.Models.ProviderLocation", b =>
                {
                    b.HasOne("ClinicFlowDemo.Models.ClinicLocation", "ClinicLocation")
                        .WithMany("ProviderLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicFlowDemo.Models.Provider", "Provider")
                        .WithMany("ProviderLocations")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClinicLocation");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("ClinicFlowDemo.Models.ProviderSpecialty", b =>
                {
                    b.HasOne("ClinicFlowDemo.Models.Provider", "Provider")
                        .WithMany("ProviderSpecialties")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicFlowDemo.Models.Specialty", "Specialty")
                        .WithMany("ProviderSpecialties")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Provider");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("ClinicFlowDemo.Models.Room", b =>
                {
                    b.HasOne("ClinicFlowDemo.Models.ClinicLocation", "ClinicLocation")
                        .WithMany("Rooms")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClinicLocation");
                });

            modelBuilder.Entity("ClinicFlowDemo.Models.Appointment", b =>
                {
                    b.Navigation("Encounter");
                });

            modelBuilder.Entity("ClinicFlowDemo.Models.ClinicLocation", b =>
                {
                    b.Navigation("ProviderLocations");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("ClinicFlowDemo.Models.DiagnosisCode", b =>
                {
                    b.Navigation("EncounterDiagnoses");
                });

            modelBuilder.Entity("ClinicFlowDemo.Models.Encounter", b =>
                {
                    b.Navigation("EncounterDiagnoses");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("ClinicFlowDemo.Models.Medication", b =>
                {
                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("ClinicFlowDemo.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("PatientPolicies");
                });

            modelBuilder.Entity("ClinicFlowDemo.Models.Policy", b =>
                {
                    b.Navigation("PatientPolicies");
                });

            modelBuilder.Entity("ClinicFlowDemo.Models.Provider", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ProviderLocations");

                    b.Navigation("ProviderSpecialties");
                });

            modelBuilder.Entity("ClinicFlowDemo.Models.Room", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("ClinicFlowDemo.Models.Specialty", b =>
                {
                    b.Navigation("ProviderSpecialties");
                });
#pragma warning restore 612, 618
        }
    }
}
